# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    versioning-strategy: "increase"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@antv/g6"
      # execa latest 7.x works only in ES module
      - dependency-name: "execa"
      # execa latest 5.x works only in ES module
      - dependency-name: "chalk"
